export enum CartActionTypes {
  ADD_TO_CART = "ADD_TO_CART",
  CLEAR_CART = "CLEAR_CART",
  COUNT_CART_TOTALS = "COUNT_CART_TOTALS",
  REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
  TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT",
}

export enum FilterActionTypes {
  LOAD_PRODUCTS = "LOAD_PRODUCTS",
  SET_LIST_VIEW = "SET_LIST_VIEW",
  SET_GRID_VIEW = "SET_GRID_VIEW",
  UPDATE_SORT = "UPDATE_SORT",
  SORT_PRODUCTS = "SORT_PRODUCTS",
  UPDATE_FILTERS = "UPDATE_FILTERS",
  FILTER_PRODUCTS = "FILTER_PRODUCTS",
  CLEAR_FILTERS = "CLEAR_FILTERS",
}

export enum ProductsActionTypes {
  SIDEBAR_OPEN = "SIDEBAR_OPEN",
  SIDEBAR_CLOSE = "SIDEBAR_CLOSE",
  GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN",
  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR",
  GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN",
  GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS",
  GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR",
}
